version: "3.9"

services:
  backend:
    build: ./backend
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    working_dir: /app
    build:
      context: .
      dockerfile: infrastructure/frontend.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
